os:
  debian:
    bookworm:
      path: /etc/apt/sources.list
      urls:
        - "deb http://mirrors.aliyun.com/debian/ bookworm main contrib non-free non-free-firmware"
    trixie:
      path: /etc/apt/sources.list
      urls:
        - "deb http://mirrors.aliyun.com/debian/ trixie main contrib non-free non-free-firmware"

  alpine:
    "3.20":
      path: /etc/apk/repositories
      urls:
        - "http://mirrors.aliyun.com/alpine/v3.20/main"
        - "http://mirrors.aliyun.com/alpine/v3.20/community"

runtime:
  python:
    all:
      path: /root/.pip/pip.conf
      urls:
        - "https://pypi.tuna.tsinghua.edu.cn/simple"
